version: '3.3'
services:
        unifi:
                container_name: Unifi.Ctrl
                restart: always
                environment:
                        - TZ=Europe/Brussels
                volumes:
                        - '/docker/unifi:/unifi'
                network_mode: 'host'
                image: 'jacobalberty/unifi:5.12.35'
        portainer:
                container_name: Portainer
                restart: always
                ports:
                    - '9000:9000'
                volumes:
                    - '/var/run/docker.sock:/var/run/docker.sock'
                    - '/docker/portainer/data:/data'
                image: portainer/portainer
        unifi-video-controller:
                container_name: Unifi.Video

                restart: always

                network_mode: 'host'
                volumes:
                    - '/docker/unifi_video/data:/var/lib/unifi-video'
                    - '/media/USB/Unifi.Video:/var/lib/unifi-video/videos'
                environment:
                    - TZ=Europe/Brussels
                    - DEBUG=1
                cap_add:
                    - SYS_ADMIN
                    - DAC_READ_SEARCH             
                image: 'pducharme/unifi-video-controller:3.10.6'
                security_opt:
                   - apparmor:unconfined
        nginx-proxy:
                container_name: nginx.proxy
                image: jc21/nginx-proxy-manager:2.5.0
                ports:
                  - 80:80
                  - 81:81
                  - 443:443
                volumes:
                  - /docker/Unifi_Controller/nginx.json:/app/config/production.json
                  - /docker/nginx/data:/data
                  - /docker/nginx/letsencrypt:/etc/letsencrypt
                depends_on:
                  - maria-db
                environment:
                  - FORCE_COLOR=1
        maria-db:
                container_name: nginx.mariadb
                image: mariadb:latest
                restart: always
                secrets:
                        - MYSQL_ROOT_PASSWORD
                        - MYSQL_PASSWORD
                environment:
                        MYSQL_ROOT_PASSWORD_FILE: '/run/secrets/MYSQL_ROOT_PASSWORD'
                        MYSQL_PASSWORD_FILE: '/run/secrets/MYSQL_PASSWORD'
                        MYSQL_DATABASE: "nginx"
                        MYSQL_USER : "npm"
                volumes:
                        - /docker/mariadb/mysql:/var/lib/mysql
        rsync-server:
                container_name: rsync.srv
                ports:
                        - 873:873
                environment:
                        - USERNAME=user
                        - PASSWORD=pass
                volumes:
                        - '/media/USB2:/data'
                image: apnar/rsync-server
secrets:
        MYSQL_ROOT_PASSWORD:
                file: /docker/Unifi_Controller/mysql_root_password
        MYSQL_PASSWORD:
                file: /docker/Unifi_Controller/mysql_password
