version: '3.3'
services:
        unifi:
                container_name: Unifi.Ctrl
                restart: always
                environment:
                        - TZ=Europe/Brussels
                volumes:
                        - '/docker/unifi:/unifi'
                network_mode: 'host'
                image: 'jacobalberty/unifi:5.11.39'
        portainer:
                container_name: Portainer
                restart: always
                ports:
                    - '9000:9000'
                volumes:
                    - '/var/run/docker.sock:/var/run/docker.sock'
                    - '/docker/portainer/data:/data'
                image: portainer/portainer
        unifi-video-controller:
                container_name: Unifi.Video
                restart: always
                network_mode: 'host'
                volumes:
                    - '/docker/unifi_video/data:/var/lib/unifi-video'
                    - '/docker/unifi_video/recordings:/var/lib/unifi-video/videos'
                environment:
                    - TZ=Europe/Brussels
                    - PUID=99
                    - PGID=100
                    - DEBUG=1
                cap_add:
                    - SYS_ADMIN
                    - DAC_READ_SEARCH
                image: pducharme/unifi-video-controller
